// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.CmsKit.Public.MarkedItems;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.MarkedItems;

public interface IMarkedItemPublicAppService : IApplicationService
{
    Task<MarkedItemWithToggleDto> GetForUserAsync(string entityType, string entityId);

    Task<bool> ToggleAsync(string entityType, string entityId);
}
