// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.CmsKit.Public.MarkedItems;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.MarkedItems;

public class MarkedItemDto
{
    public string IconName { get; set; }
}
