// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.CmsKit.Public.Ratings;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.Ratings;

public class RatingWithStarCountDto
{
    public Int16 StarCount { get; set; }

    public int Count { get; set; }

    public bool IsSelectedByCurrentUser { get; set; }
}
