<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\configureawait.props" />
  <Import Project="..\..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.PermissionManagement.Blazor.MudBlazor\Volo.Abp.PermissionManagement.Blazor.MudBlazor.csproj" />
    <ProjectReference Include="..\..\..\..\framework\src\Volo.Abp.AspNetCore.Components.WebAssembly.Theming.MudBlazor\Volo.Abp.AspNetCore.Components.WebAssembly.Theming.MudBlazor.csproj" />
    <ProjectReference Include="..\Volo.Abp.PermissionManagement.HttpApi.Client\Volo.Abp.PermissionManagement.HttpApi.Client.csproj" />
  </ItemGroup>

</Project>
