// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.Docs.Common.Documents;

// ReSharper disable once CheckNamespace
namespace Volo.Docs.Documents;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDocumentPdfAppService), typeof(DocsDocumentPdfClientProxy))]
public partial class DocsDocumentPdfClientProxy : ClientProxyBase<IDocumentPdfAppService>, IDocumentPdfAppService
{
    public virtual async Task<IRemoteStreamContent> DownloadPdfAsync(DocumentPdfGeneratorInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(DownloadPdfAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DocumentPdfGeneratorInput), input }
        });
    }

    public virtual async Task<bool> ExistsAsync(DocumentPdfGeneratorInput input)
    {
        return await RequestAsync<bool>(nameof(ExistsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DocumentPdfGeneratorInput), input }
        });
    }
}
