name: 🐞 Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! This template will help us gather the information we need to start the triage process.
        
        Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting **non-security** bugs and feature requests.
        If you believe you have an issue that affects the SECURITY of the platform, please do NOT create an issue and instead email your issue details to info@abp.io.
        For other types of questions, consider using [StackOverflow](https://stackoverflow.com/questions/tagged/abp).
  - type: checkboxes
    id: searched
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered ([abp/issues](https://github.com/abpframework/abp/issues)).
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: false
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        Did this work in a previous build or release of ABP framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
      placeholder: Regression?
    validations:
      required: false
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: |
        Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Configuration
        Please provide more information on your ABP configuration.
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of ABP is the code running on?
      placeholder: Version
    validations:
      required: true
  - type: dropdown
    id: user-interface
    attributes:
      label: User Interface
      description: Which user interface of ABP is related to the problem?
      options:
        - Common (Default)
        - MVC
        - Angular
        - Blazor
        - Blazor Server
        - React Native
        - MAUI
    validations:
      required: true
  - type: dropdown
    id: database-provider
    attributes:
      label: Database Provider
      description: Which database provider of ABP is used?
      options:
        - EF Core (Default)
        - MongoDB
        - None/Others
    validations:
      required: true
  - type: dropdown
    id: structure
    attributes:
      label: Tiered or separate authentication server
      description: Which structure of ABP is specified?
      options:
        - None (Default)
        - Tiered
        - Separate Auth Server
    validations:
      required: true
  - type: dropdown
    id: Operation-System
    attributes:
      label: Operation System
      description: What is the operation system of the server?
      options:
        - Windows (Default)
        - Linux
        - macOS
        - Others
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Other information
    validations:
      required: false
