IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [QRTZ_CALENDARS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [CALENDAR_NAME] nvarchar(100) NOT NULL,
    [CALENDAR] varbinary(max) NOT NULL,
    CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY ([SCHED_NAME], [CALENDAR_NAME])
);
GO

CREATE TABLE [QRTZ_FIRED_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [ENTRY_ID] nvarchar(140) NOT NULL,
    [TRIGGER_NAME] nvarchar(200) NOT NULL,
    [TRIGGER_GROUP] nvarchar(200) NOT NULL,
    [INSTANCE_NAME] nvarchar(200) NOT NULL,
    [FIRED_TIME] bigint NOT NULL,
    [SCHED_TIME] bigint NOT NULL,
    [PRIORITY] int NOT NULL,
    [STATE] nvarchar(16) NOT NULL,
    [JOB_NAME] nvarchar(150) NULL,
    [JOB_GROUP] nvarchar(150) NULL,
    [IS_NONCONCURRENT] bit NULL,
    [REQUESTS_RECOVERY] bit NULL,
    CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [ENTRY_ID])
);
GO

CREATE TABLE [QRTZ_JOB_DETAILS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [JOB_NAME] nvarchar(150) NOT NULL,
    [JOB_GROUP] nvarchar(150) NOT NULL,
    [DESCRIPTION] nvarchar(250) NULL,
    [JOB_CLASS_NAME] nvarchar(250) NOT NULL,
    [IS_DURABLE] bit NOT NULL,
    [IS_NONCONCURRENT] bit NOT NULL,
    [IS_UPDATE_DATA] bit NOT NULL,
    [REQUESTS_RECOVERY] bit NOT NULL,
    [JOB_DATA] varbinary(max) NULL,
    CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP])
);
GO

CREATE TABLE [QRTZ_LOCKS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [LOCK_NAME] nvarchar(40) NOT NULL,
    CONSTRAINT [PK_QRTZ_LOCKS] PRIMARY KEY ([SCHED_NAME], [LOCK_NAME])
);
GO

CREATE TABLE [QRTZ_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_GROUP])
);
GO

CREATE TABLE [QRTZ_SCHEDULER_STATE] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [INSTANCE_NAME] nvarchar(200) NOT NULL,
    [LAST_CHECKIN_TIME] bigint NOT NULL,
    [CHECKIN_INTERVAL] bigint NOT NULL,
    CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY ([SCHED_NAME], [INSTANCE_NAME])
);
GO

CREATE TABLE [QRTZ_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_NAME] nvarchar(150) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    [JOB_NAME] nvarchar(150) NOT NULL,
    [JOB_GROUP] nvarchar(150) NOT NULL,
    [DESCRIPTION] nvarchar(250) NULL,
    [NEXT_FIRE_TIME] bigint NULL,
    [PREV_FIRE_TIME] bigint NULL,
    [PRIORITY] int NULL,
    [TRIGGER_STATE] nvarchar(16) NOT NULL,
    [TRIGGER_TYPE] nvarchar(8) NOT NULL,
    [START_TIME] bigint NOT NULL,
    [END_TIME] bigint NULL,
    [CALENDAR_NAME] nvarchar(200) NULL,
    [MISFIRE_INSTR] smallint NULL,
    [JOB_DATA] varbinary(max) NULL,
    CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]),
    CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS_SCHED_NAME_JOB_NAME_JOB_GROUP] FOREIGN KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]) REFERENCES [QRTZ_JOB_DETAILS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]) ON DELETE CASCADE
);
GO

CREATE TABLE [QRTZ_BLOB_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_NAME] nvarchar(150) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    [BLOB_DATA] varbinary(max) NULL,
    CONSTRAINT [PK_QRTZ_BLOB_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]),
    CONSTRAINT [FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);
GO

CREATE TABLE [QRTZ_CRON_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_NAME] nvarchar(150) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    [CRON_EXPRESSION] nvarchar(250) NOT NULL,
    [TIME_ZONE_ID] nvarchar(80) NULL,
    CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]),
    CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);
GO

CREATE TABLE [QRTZ_SIMPLE_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_NAME] nvarchar(150) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    [REPEAT_COUNT] bigint NOT NULL,
    [REPEAT_INTERVAL] bigint NOT NULL,
    [TIMES_TRIGGERED] bigint NOT NULL,
    CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]),
    CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);
GO

CREATE TABLE [QRTZ_SIMPROP_TRIGGERS] (
    [SCHED_NAME] nvarchar(120) NOT NULL,
    [TRIGGER_NAME] nvarchar(150) NOT NULL,
    [TRIGGER_GROUP] nvarchar(150) NOT NULL,
    [STR_PROP_1] nvarchar(512) NULL,
    [STR_PROP_2] nvarchar(512) NULL,
    [STR_PROP_3] nvarchar(512) NULL,
    [INT_PROP_1] int NULL,
    [INT_PROP_2] int NULL,
    [LONG_PROP_1] bigint NULL,
    [LONG_PROP_2] bigint NULL,
    [DEC_PROP_1] decimal(13,4) NULL,
    [DEC_PROP_2] decimal(13,4) NULL,
    [BOOL_PROP_1] bit NULL,
    [BOOL_PROP_2] bit NULL,
    [TIME_ZONE_ID] nvarchar(80) NULL,
    CONSTRAINT [PK_QRTZ_SIMPROP_TRIGGERS] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]),
    CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);
GO

CREATE INDEX [IDX_QRTZ_FT_G_J] ON [QRTZ_FIRED_TRIGGERS] ([SCHED_NAME], [JOB_GROUP], [JOB_NAME]);
GO

CREATE INDEX [IDX_QRTZ_FT_G_T] ON [QRTZ_FIRED_TRIGGERS] ([SCHED_NAME], [TRIGGER_GROUP], [TRIGGER_NAME]);
GO

CREATE INDEX [IDX_QRTZ_FT_INST_JOB_REQ_RCVRY] ON [QRTZ_FIRED_TRIGGERS] ([SCHED_NAME], [REQUESTS_RECOVERY]);
GO

CREATE INDEX [IDX_QRTZ_T_C] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [CALENDAR_NAME]);
GO

CREATE INDEX [IDX_QRTZ_T_G_J] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [JOB_GROUP], [JOB_NAME]);
GO

CREATE INDEX [IDX_QRTZ_T_N_G_STATE] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_GROUP], [TRIGGER_STATE]);
GO

CREATE INDEX [IDX_QRTZ_T_N_STATE] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP], [TRIGGER_STATE]);
GO

CREATE INDEX [IDX_QRTZ_T_NEXT_FIRE_TIME] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [NEXT_FIRE_TIME]);
GO

CREATE INDEX [IDX_QRTZ_T_NFT_ST] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_STATE], [NEXT_FIRE_TIME]);
GO

CREATE INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [MISFIRE_INSTR], [NEXT_FIRE_TIME], [TRIGGER_STATE]);
GO

CREATE INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE_GRP] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [MISFIRE_INSTR], [NEXT_FIRE_TIME], [TRIGGER_GROUP], [TRIGGER_STATE]);
GO

CREATE INDEX [IDX_QRTZ_T_STATE] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_STATE]);
GO

CREATE INDEX [IX_QRTZ_TRIGGERS_SCHED_NAME_JOB_NAME_JOB_GROUP] ON [QRTZ_TRIGGERS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20210726171146_InitMigration', N'5.0.8');
GO

COMMIT;
GO

