// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.CmsKit.Public.GlobalResources;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.GlobalResources.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGlobalResourcePublicAppService), typeof(GlobalResourcePublicClientProxy))]
public partial class GlobalResourcePublicClientProxy : ClientProxyBase<IGlobalResourcePublicAppService>, IGlobalResourcePublicAppService
{
    public virtual async Task<GlobalResourceDto> GetGlobalScriptAsync()
    {
        return await RequestAsync<GlobalResourceDto>(nameof(GetGlobalScriptAsync));
    }

    public virtual async Task<GlobalResourceDto> GetGlobalStyleAsync()
    {
        return await RequestAsync<GlobalResourceDto>(nameof(GetGlobalStyleAsync));
    }
}
