// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.CmsKit.Contents;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.Pages.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPagePublicAppService), typeof(PagesPublicClientProxy))]
public partial class PagesPublicClientProxy : ClientProxyBase<IPagePublicAppService>, IPagePublicAppService
{
    public virtual async Task<PageDto> FindBySlugAsync(string slug)
    {
        return await RequestAsync<PageDto>(nameof(FindBySlugAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), slug }
        });
    }
}
