export const enum ePropType {
  Boolean = 'boolean',
  Date = 'date',
  DateTime = 'datetime',
  Email = 'email',
  Enum = 'enum',
  Hidden = 'hidden',
  MultiSelect = 'multiselect',
  Number = 'number',
  Password = 'password',
  String = 'string',
  Text = 'text',
  Time = 'time',
  Typeahead = 'typeahead',
}
