// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.AbpWebSite.EntityFrameworkCore;

namespace Volo.AbpWebSite.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AbpWebSiteDbContext))]
    [Migration("20180715113144_DownloadInfo_TemplateName_And_DatabaseProvider")]
    partial class DownloadInfo_TemplateName_And_DatabaseProvider
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Volo.Docs.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultDocumentName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("DocumentStoreType");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Format");

                    b.Property<string>("GoogleCustomSearchId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("NavigationDocumentName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("DocsProjects");
                });

            modelBuilder.Entity("Volo.Utils.SolutionTemplating.DownloadInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreationDuration");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<byte>("DatabaseProvider");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(42);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
