// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.CmsKit.Public.Comments;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.Comments;

public class UpdateCommentInput : ExtensibleObject
{
    public string Text { get; set; }

    public string ConcurrencyStamp { get; set; }

    public Guid? CaptchaToken { get; set; }

    public int CaptchaAnswer { get; set; }
}
