import { makeEnvironmentProviders } from '@angular/core';
import {
  SETTING_MANAGEMENT_FEATURES_PROVIDERS,
  SETTING_MANAGEMENT_ROUTE_PROVIDERS,
  SETTING_MANAGEMENT_SETTING_TAB_PROVIDERS,
  SETTING_MANAGEMENT_VISIBLE_PROVIDERS,
} from './';

export function provideSettingManagementConfig() {
  return makeEnvironmentProviders([
    SETTING_MANAGEMENT_ROUTE_PROVIDERS,
    SETTING_MANAGEMENT_SETTING_TAB_PROVIDERS,
    SETTING_MANAGEMENT_FEATURES_PROVIDERS,
    SETTING_MANAGEMENT_VISIBLE_PROVIDERS,
  ]);
}
