export const SYSTEM_TYPES = new Map([
  ['Bool', 'boolean'],
  ['Byte', 'number'],
  ['Char', 'string'],
  ['Collections.Generic.Dictionary', 'Record'],
  ['DateTime', 'string'],
  ['DateTimeOffset', 'string'],
  ['Decimal', 'number'],
  ['Double', 'number'],
  ['Guid', 'string'],
  ['Int16', 'number'],
  ['Int32', 'number'],
  ['Int64', 'number'],
  ['Net.HttpStatusCode', 'number'],
  ['Object', 'object'],
  ['Sbyte', 'number'],
  ['Single', 'number'],
  ['String', 'string'],
  ['TimeSpan', 'string'],
  ['UInt16', 'number'],
  ['UInt32', 'number'],
  ['UInt64', 'number'],
  ['Void', 'void'],
]);
