// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.CmsKit.Public.Reactions;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.Reactions;

public interface IReactionPublicAppService : IApplicationService
{
    Task<ListResultDto<ReactionWithSelectionDto>> GetForSelectionAsync(string entityType, string entityId);

    Task CreateAsync(string entityType, string entityId, string reaction);

    Task DeleteAsync(string entityType, string entityId, string reaction);
}
