// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.CmsKit.Public.Reactions;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.Reactions;

public class ReactionDto
{
    public string Name { get; set; }

    public string DisplayName { get; set; }
}
