<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DistDemoApp</RootNamespace>
    <DistDemoDbProvider>MongoDb</DistDemoDbProvider>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\src\Volo.Abp.MongoDB\Volo.Abp.MongoDB.csproj" />
    <ProjectReference Include="..\DistDemoApp.Shared\DistDemoApp.Shared.csproj" />
  </ItemGroup>

</Project>
