apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  selector:
    matchLabels:
      app: auth-server
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: "volosoft/microservice-demo-auth-server"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:51511
          - name: ConnectionStrings__Default
            value: Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
          - name: RabbitMQ__Connections__Default__HostName
            value: rabbitmq
          - name: Redis__Configuration
            value: redis
          ports:
            - name: http
              containerPort: 51511