apiVersion: v1
kind: Service
metadata:
  name: auth-server-expose
spec:
  type: LoadBalancer
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 51511
      targetPort: 51511
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-admin-app-expose
spec:
  type: LoadBalancer
  selector:
    app: backend-admin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: public-website-expose
spec:
  type: LoadBalancer
  selector:
    app: public-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003