apiVersion: v1
kind: Service
metadata:
  name: auth-server-expose
spec:
  type: NodePort
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 51511
      targetPort: 51511
---
apiVersion: v1
kind: Service
metadata:
  name: backend-admin-app-expose
spec:
  type: NodePort
  selector:
    app: backend-admin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: public-website-expose
spec:
  type: NodePort
  selector:
    app: public-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80