apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: "volosoft/microservice-demo-identity-service"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: AuthServer__Authority
            value: http://auth-server:51511
          - name: ConnectionStrings__Default
            value: Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
          - name: RabbitMQ__Connections__Default__HostName
            value: rabbitmq
          - name: Redis__Configuration
            value: redis
          ports:
            - name: http
              containerPort: 80