apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-website-gateway
spec:
  selector:
    matchLabels:
      app: public-website-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: public-website-gateway
    spec:
      containers:
        - name: public-website-gateway
          image: "volosoft/microservice-demo-public-website-gateway"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: AuthServer__Authority
            value: http://auth-server:51511
          - name: ConnectionStrings__Default
            value: Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
          - name: GlobalConfiguration__BaseUrl
            value: http://public-website-gateway
          - name: ReRoutes__0__DownstreamHostAndPorts__0__Host
            value: product-service
          - name: ReRoutes__0__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: ReRoutes__1__DownstreamHostAndPorts__0__Host
            value: blogging-service
          - name: ReRoutes__1__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Redis__Configuration
            value: redis
          ports:
            - name: http
              containerPort: 80