// <auto-generated/>
#pragma warning disable 1591
namespace Volo.Abp.AspNetCore.RazorViews
{
    #line hidden
    using System;
    using System.Threading.Tasks;
#nullable restore
#line 1 "MultiTenancyMiddlewareErrorPage.cshtml"
using System.Globalization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "MultiTenancyMiddlewareErrorPage.cshtml"
using Volo.Abp.AspNetCore.MultiTenancy.Views;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "MultiTenancyMiddlewareErrorPage.cshtml"
using Volo.Abp.AspNetCore.RazorViews;

#line default
#line hidden
#nullable disable
    internal class MultiTenancyMiddlewareErrorPage : AbpCompilationRazorPageBase
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 5 "MultiTenancyMiddlewareErrorPage.cshtml"
  
    Response.ContentType = "text/html; charset=utf-8";
    Response.StatusCode = 404;

#line default
#line hidden
#nullable disable
            WriteLiteral("\n");
            WriteLiteral("\n<html");
            BeginWriteAttribute("lang", " lang=\"", 453, "\"", 512, 1);
#nullable restore
#line 19 "MultiTenancyMiddlewareErrorPage.cshtml"
WriteAttributeValue("", 460, HtmlEncoder.Encode(CultureInfo.CurrentCulture.Name), 460, 52, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">\n    <head>\n        <meta charset=\"utf-8\" />\n        <title>");
#nullable restore
#line 22 "MultiTenancyMiddlewareErrorPage.cshtml"
          Write(HtmlEncoder.Encode(Model.Message));

#line default
#line hidden
#nullable disable
            WriteLiteral("</title>\n    </head>\n    <body>\n        <h3>");
#nullable restore
#line 25 "MultiTenancyMiddlewareErrorPage.cshtml"
       Write(HtmlEncoder.Encode(Model.Message));

#line default
#line hidden
#nullable disable
            WriteLiteral("</h3>\n        <p>");
#nullable restore
#line 26 "MultiTenancyMiddlewareErrorPage.cshtml"
      Write(HtmlEncoder.Encode(Model.Details));

#line default
#line hidden
#nullable disable
            WriteLiteral("<p/>\n    </body>\n</html>\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 10 "MultiTenancyMiddlewareErrorPage.cshtml"
           
    public MultiTenancyMiddlewareErrorPage(MultiTenancyMiddlewareErrorPageModel model)
    {
        Model = model;
    }

    public MultiTenancyMiddlewareErrorPageModel Model { get; set; }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
