name: Compress Images
on:
  pull_request:
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"
      - "**.gif"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository && !github.event.pull_request.draft
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
