name: Documentation Checks

on:
  push:
    branches:
      - dev
    paths:
      # This ensures the check will only be run when something changes in the docs content
      - "docs/en/**/*"
  pull_request:
    branches:
      - dev
    paths:
      - "docs/en/**/*"
permissions:
  contents: read  #  to fetch code (actions/checkout)
jobs:
  spellcheck:
    name: "Docs: Spellcheck (En)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "16"
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./cSpell.json "docs/en/**/*.md" --no-progress # Update for path to the markdown files
        name: Run cSpell
